services:
  app:
    command: sh -c "npm install && npm run start:dev"
    build: 
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: dev
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
